version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  api:
    build: .
    container_name: api
    ports:
      - "5005:5005"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=127.0.0.1
      - REDIS_PORT=6379
    command: npm run dev
    restart: always

  worker:
    build: .
    depends_on:
      - redis
    environment:
      - REDIS_HOST=127.0.0.1
      - REDIS_PORT=6379
    command: npm run worker
    restart: always